newsait/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('search', views.catalog, name='search'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

newsait/newsait/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'main.views.my_404_view'

urlpatterns = [
    path('product/', include('CatalogApp.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsait/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order')
]

newsait/orders/models.py
from django.db import models

from CatalogApp.models import Products
from users.models import User

class OrderItemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(basket.products_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name='Пользователь', default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    delivery_address = models.CharField(max_length=255, verbose_name='Адрес доставки')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.first_name} {self.last_name}'

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Продукт', default=None)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.product.name} | Заказ № {self.order.pk}'

newsait/orders/forms.py
import re

from django import forms

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    delivery_address = forms.CharField()

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
        pattern = re.compile(r'^\d{11}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")

        return data


    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя",
    #         }
    #     )
    # )
    #
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите вашу фамилию",
    #         }
    #     )
    # )
    #
    # phone_number = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #         }
    #     )
    # )
    #
    # delivery_address = forms.CharField(
    #     widget=forms.Textarea(
    #         attrs={
    #             "class": "form-control",
    #             "id": "delivery-address",
    #             "rows": 2,
    #             "placeholder": "Введите адрес",
    #         }
    #     )
    # )

newsait/orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.db import transaction
from basket.models import Basket
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from django.forms import ValidationError
from django.contrib import messages

@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Basket.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            first_name=form.cleaned_data['first_name'],
                            last_name=form.cleaned_data['last_name'],
                            phone_number=form.cleaned_data['phone_number'],
                            delivery_address=form.cleaned_data['delivery_address']
                        )
                        for cart_item in cart_items:
                            product = cart_item.product
                            price = cart_item.product.cost
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточное количество товара {product.name} на складе\
                                                        В наличии - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        cart_items.delete()

                        messages.success(request, 'Заказ оформлен')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('orders:create_orders')
    else:
        form = CreateOrderForm()

    context = {
        'form': form
    }
    return render(request, 'orders/create_order.html', context=context)

newsait/orders/templates/orders/create_order.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}
Оформление заказа
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger fade show">{{message}}</div>
    {% endfor %}
    {% endif %}
            <div class="row mt-1">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <!-- Контент на странице -->
                    <div class=" bg-white mb-4 mx-2 rounded custom-shadow">
                        <div class="container">
                            <h3 class="text-center mb-4">Выбранные товары</h3>
                            <div class="container" id="cart-items-container">
                                <!-- Разметка корзины -->
                                    {% include "basket/includes/included_cart.html" %}
                                <!-- Закончилась разметка корзины -->
                            </div>
                        </div>
                        <!-- Детали заказа -->
                        <div class="container">
                            <h3 class="text-center">Детали заказа</h3>
                            <div class="mb-3 col-lg-12 col-md-12 col-sm-12" style="border:1px solid;border-radius:30px;padding:20px;">
                                <div class="card-body">
                                    <form action="{% url 'orders:create_order' %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Имя*:</label>
                                                <input type="text" class="form-control" id="id_first_name"
                                                    name="first_name" value="{% if form.first_name.value %}{{form.first_name.value}}{% endif %}" placeholder="Введите имя" required>
                                                {% if form.first_name.errors %}
                                                <div class="alert alert-danger fade show">{{form.first_name.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Фамилия*:</label>
                                                <input type="text" class="form-control" id="id_last_name" name="last_name" value="{% if form.last_name.value %}{{form.last_name.value}}{% endif %}" placeholder="Введите фамилию" required>
                                                {% if form.last_name.errors %}
                                                <div class="alert alert-danger fade show">{{form.last_name.errors}}</div>
                                                {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                                    placeholder="В формате: XXX-XXX-XX-XX" value="{% if form.phone_number.value %}{{form.phone_number.value}}{% endif %}"
                                                    required>
                                                {% if form.phone_number.errors %}
                                                <div class="alert alert-danger fade show">{{form.phone_number.errors}}</div>
                                                {% endif %}
                                            </div>

                                            <div class="mb-3" id="deliveryAddressField">
                                                <label for="id_delivery_address" class="form-label">Адрес
                                                    доставки*:</label>
                                                <textarea class="form-control" id="id_delivery_address"
                                                    name="delivery_address" rows="2" required></textarea>
                                            </div>

                                        </div>
                                        <button type="submit" class="btn orange" style="background: rgba(255, 138, 0,0.5);">Оформить заказ</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}