newsait/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('search', views.catalog, name='search'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

newsait/newsait/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'main.views.my_404_view'

urlpatterns = [
    path('product/', include('CatalogApp.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsait/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users-basket', views.users_basket, name='users-basket')
]

newsait/orders/models.py
from django.db import models

from CatalogApp.models import Products
from users.models import User

class OrderItemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(basket.products_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, verbose_name='Пользователь', default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    delivery_address = models.CharField(max_length=255, verbose_name='Адрес доставки')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.first_name} {self.last_name}'

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Продукт', default=None)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    class Meta:
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.product.name} | Заказ № {self.order.pk}'

newsait/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name="Аватар")

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

newsait/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from users.models import User
from django import forms

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['image', 'username']

newsait/users/views.py
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render
from users.forms import UserLoginForm, UserRegistrationForm,UserProfileForm
from django.contrib import auth
from django.urls import reverse
from django.contrib import messages
from users.models import User
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from orders.models import Order, OrderItem

def login(request):
    message = request.GET.get('message', None)
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.add_message(request, messages.INFO, f'{user} вы успешно вошли в аккаунт')
                return HttpResponseRedirect(reverse('home'))
        else:
            messages.error(request, 'Неправильный никнейм или пароль. Попробуйте еще раз', extra_tags='password_login')
    else:
        form = UserLoginForm()
    if message:
        message = 'Пожалуйста войдите в аккаунт, чтобы добавить товар в корзину'
        context = {
            'title': 'Авторизация',
            'form': form,
            'message': message
        }
    else:
        context = {
            'title': 'Авторизация',
            'form': form,
        }

    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid() and (form.data['password1'] == form.data['password2']) and not(form.data['email'] in User.objects.all().values_list('email', flat=True)):
            form.save()
            send_mail(
                'Регистрация на сайте',
                'Вы успешно зарегистрировались на сайте. Ваш логин: {}, пароль: {}'.format(form.data['username'],
                                                                                           form.data['password1']),
                'fruit_test_db@mail.ru',
                [form.data['email']],
                fail_silently=False,
            )
            messages.add_message(request, messages.INFO, f'{form.data["username"]} вы успешно создали в аккаунт')
            return HttpResponseRedirect(reverse('user:login'))
        else:
            if form.data['username'] in User.objects.all().values_list('username', flat=True):
                messages.error(request, 'Никнейм занят. Введите другой', extra_tags="username")
            elif form.data['email'] in User.objects.all().values_list('email', flat=True):
                messages.error(request, 'Почта занята. Введите другую', extra_tags="email")
            elif form.errors.as_data() == {'password2'}:
                messages.error(request, 'Пароль короче 8 символов или содержит только цифры', extra_tags="password")
            elif form.data['password1'] != form.data['password2']:
                messages.error(request, 'Пароли не совпадают', extra_tags="passwords")
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form,
    }

    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            messages.error(request, 'Неправильный никнейм или пароль. Попробуйте еще раз', extra_tags='password_login')
    else:
        form = UserProfileForm(instance=request.user)

    orders = (
        Order.objects.filter(user=request.user)
        .prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        )
        .order_by("-id")
    )
    context = {
        'title': 'Профиль пользователя',
        'form': form,
        'orders': orders
    }

    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    auth.logout(request)

    return HttpResponseRedirect(reverse('home'))

def users_basket(request):
    return render(request,'users/users_basket.html')

newsait/users/templates/users/login.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
{{title}}
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-6 col-md-6 col-lg-5 mx-auto">
        <form class="text-center align-items-center" style="border-radius:20px;border:solid 1px;padding:20px;" action="{% url 'user:login' %}" method="post">
            {% csrf_token %}
            <svg width="64px" height="64px" viewBox="0 0 100 100" class="looka-1j8o68f mb-2" id="image_footer">
                <defs id="SvgjsDefs4396">
                    <linearGradient id="SvgjsLinearGradient4401">
                        <stop id="SvgjsStop4402" stop-color="#ef4136" offset="0"></stop>
                        <stop id="SvgjsStop4403" stop-color="#fbb040" offset="1"></stop>
                    </linearGradient>
                </defs>
                <g id="SvgjsG4397" featurekey="symbolFeature-0"
                   transform="matrix(1.1096069569186666,0,0,1.1096069569186666,-5.758862815409239,-5.228467862481947)"
                   fill="url(#SvgjsLinearGradient4401)">
                    <path xmlns="http://www.w3.org/2000/svg"
                          d="M85.324,52.012H57.902c-0.868,0-1.303,1.049-0.689,1.663l19.47,19.47c0.403,0.403,1.074,0.382,1.439-0.055  c4.876-5.84,7.605-12.865,8.181-20.034C86.347,52.493,85.89,52.012,85.324,52.012z M54.457,56.432  c-0.614-0.614-1.663-0.179-1.663,0.689v27.732c0,0.569,0.487,1.028,1.054,0.977c7.203-0.649,14.247-3.468,20.066-8.466  c0.428-0.368,0.444-1.031,0.045-1.43L54.457,56.432z M43.788,52.012l-27.882,0c-0.566,0-1.023,0.481-0.978,1.044  c0.583,7.274,3.381,14.403,8.393,20.293c0.367,0.431,1.033,0.449,1.433,0.048l19.723-19.723  C45.091,53.062,44.656,52.012,43.788,52.012z M47.233,56.432L27.522,76.143c-0.402,0.402-0.383,1.07,0.052,1.436  c5.898,4.969,13.02,7.73,20.281,8.287c0.563,0.043,1.041-0.414,1.041-0.978V57.121C48.896,56.253,47.847,55.818,47.233,56.432z   M15.911,47.942h27.422c0.868,0,1.303-1.049,0.689-1.663l-19.47-19.47c-0.403-0.403-1.074-0.382-1.439,0.055  c-4.876,5.84-7.605,12.865-8.181,20.034C14.888,47.461,15.346,47.942,15.911,47.942z M46.778,43.523  c0.614,0.614,1.663,0.179,1.663-0.689V15.102c0-0.569-0.487-1.028-1.054-0.977c-7.203,0.649-14.247,3.468-20.066,8.466  c-0.428,0.368-0.444,1.031-0.045,1.43L46.778,43.523z M57.447,47.942l27.882,0c0.566,0,1.023-0.481,0.978-1.044  c-0.583-7.274-3.381-14.403-8.393-20.293c-0.367-0.431-1.033-0.449-1.433-0.048L56.758,46.279  C56.145,46.893,56.579,47.942,57.447,47.942z M54.003,43.523l19.711-19.711c0.402-0.402,0.382-1.07-0.052-1.436  c-5.898-4.969-13.02-7.73-20.281-8.287c-0.563-0.043-1.041,0.414-1.041,0.978v27.768C52.339,43.702,53.389,44.136,54.003,43.523z   M52.686,4.712c-25.746,0-47.496,20.635-47.496,45.061c0,24.847,20.214,45.061,45.061,45.061s45.061-20.214,45.061-45.061  C95.311,24.083,76.986,4.712,52.686,4.712z M50.25,89.962c-22.161,0-40.189-18.029-40.189-40.189  c0-21.409,19.918-40.189,42.625-40.189c21.523,0,37.754,17.278,37.754,40.189C90.439,71.933,72.41,89.962,50.25,89.962z"></path>
                </g>
            </svg>
            <h1 class="h3 mb-3 fw-normal">{{title}}</h1>
            {% if message %}
            <div class="alert alert-danger fade show mx-auto">{{message}}</div>
            {% endif %}
            <div class="form-floating">
                <input type="text" class="form-control mb-2" id="username" name="username" autocomplete="username" placeholder="username" required value="{% if form.username.value %}{{form.username.value}}{% endif %}">
                <label for="username">Никнейм</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control mb-2" id="password" name="password" autocomplete="current-password" placeholder="Password" required>
                <label for="password">Пароль</label>
            </div>
            <button class="btn orange my-2" type="submit" style="background: rgba(255, 138, 0,0.5)">Войти в аккаунт
            </button>
            <br>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'password_login error' %}
                    <div class="alert alert-danger fade show"{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
                    {% else %}
                    <div class="alert alert-success fade show"{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endif %}
            {% endfor %}
            {% endif %}
            <a href="{% url 'user:registration' %}" class="link-danger" style="text-decoration:none;transition: all 1s ease-in;">Нет аккаунта</a>
        </form>
    </div>
</div>
{% endblock %}

newsait/users/templates/users/logout.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    {{title}}
{% endblock %}

newsait/users/templates/users/profile.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    {{title}}
{% endblock %}
{% block content %}

    <section>
        <!-- Контент -->
        <div class="container">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success fade show" {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
                {% endfor %}
            {% endif %}
            <div class="row mt-1">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="">
                                <!-- Профиль с данными пользователя -->
                                <div class="col-md-12 col-lg-6 col-sm-8 mx-auto">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                                        <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12 col-lg-12 mb-3 text-center">
                                                    <img src="{% if user.image %}{{user.image.url}}{% else %}{% static 'main/img/anonymous.png' %}{% endif %}"
                                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                        style="max-width: 150px;">
                                                </div>

                                                <div class="col-md-12 col-lg-12 mb-3">
                                                    <label for="id_image" class="form-label">Аватар пользователя</label>
                                                    <input type="file" class="form-control mt-1 mb-1" id="id_image" name="image"
                                                        accept="image/*">
                                                    <label for="username" class="form-label">Имя пользователя*</label>
                                                    <input type="text" class="form-control" id="username" name="username"
                                                        placeholder="Введите имя пользователя" value="{{user.username}}" required>
                                                </div>
                                                <div class="col-md-12 col-lg-12 mb-3">
                                                    {% if user.email %}{{user.email}}{% else %}Нет почты{% endif %}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12 col-md-8 col-sm-3">
                                            <button type="submit" class="btn btn-success">Сохранить</button>

                                            {% if user.is_superuser %}
                                                <a href="{% url 'admin:index' %}" class="btn orange nal_margin" style="background-color: rgba(255, 138, 0,0.5);">Войти в админ панель</a>
                                            {% endif %}
                                                    </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <!-- Оформленные заказы -->
                                <div class="col-md-12">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Мои заказы</h3>
                                        <!-- Разметка заказов -->
                                        <div class="container">
                                            <div class="accordion" id="accordionExample">
                                                {% for order in orders %}
                                                <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading{{ order.id }}">
                                                        <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{order.id}}" aria-expanded="false" aria-controls="collapse{{order.id}}">
                                                            Заказ № {{order.id}} - {{order.created_timestamp}} | Статус:<strong class="mx-2">{{order.status}}</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse{{order.id}}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{order.id}}" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-dark table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Товар</th>
                                                                        <th>Количество</th>
                                                                        <th>Цена</th>
                                                                        <th>Общая стоимость</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    {% for item in order.orderitem_set.all %}
                                                                    <tr>
                                                                        <td><a class="text-white" href="product/{{item.product.slug}}">{{item.product.name}}</a></td>
                                                                        <td>{{item.quantity}}</td>
                                                                        <td>{{item.price}} ₽</td>
                                                                        <td>{{item.products_price}} ₽</td>

                                                                    </tr>
                                                                    {% endfor %}
                                                                </tbody>
                                                            </table>
                                                            <div class="d-flex justify-content-between">
                                                                <p><strong>Итого:</strong></p>
                                                                <p><strong>255.00 ₽</strong></p>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <!-- Закончилась разметка заказов -->
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 text-center">
                                    <a href="{% url 'user:logout' %}">
                                    <button class="btn btn-danger mx-auto">Разлогиниться</button>
                                    </a>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

newsait/users/templates/users/registration.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    {{title}}
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-6 col-md-6 col-lg-5 mx-auto" >
  <form class="text-center align-items-center" style="border-radius:20px;border:solid 1px;padding:20px;" action="{% url 'user:registration' %}" method="post">
    {% csrf_token %}
    <svg width="64px" height="64px" viewBox="0 0 100 100" class="looka-1j8o68f mb-2" id="image_footer">
                    <defs id="SvgjsDefs4396">
                        <linearGradient id="SvgjsLinearGradient4401">
                            <stop id="SvgjsStop4402" stop-color="#ef4136" offset="0"></stop>
                            <stop id="SvgjsStop4403" stop-color="#fbb040" offset="1"></stop>
                        </linearGradient>
                    </defs>
                    <g id="SvgjsG4397" featurekey="symbolFeature-0"
                       transform="matrix(1.1096069569186666,0,0,1.1096069569186666,-5.758862815409239,-5.228467862481947)"
                       fill="url(#SvgjsLinearGradient4401)">
                        <path xmlns="http://www.w3.org/2000/svg"
                              d="M85.324,52.012H57.902c-0.868,0-1.303,1.049-0.689,1.663l19.47,19.47c0.403,0.403,1.074,0.382,1.439-0.055  c4.876-5.84,7.605-12.865,8.181-20.034C86.347,52.493,85.89,52.012,85.324,52.012z M54.457,56.432  c-0.614-0.614-1.663-0.179-1.663,0.689v27.732c0,0.569,0.487,1.028,1.054,0.977c7.203-0.649,14.247-3.468,20.066-8.466  c0.428-0.368,0.444-1.031,0.045-1.43L54.457,56.432z M43.788,52.012l-27.882,0c-0.566,0-1.023,0.481-0.978,1.044  c0.583,7.274,3.381,14.403,8.393,20.293c0.367,0.431,1.033,0.449,1.433,0.048l19.723-19.723  C45.091,53.062,44.656,52.012,43.788,52.012z M47.233,56.432L27.522,76.143c-0.402,0.402-0.383,1.07,0.052,1.436  c5.898,4.969,13.02,7.73,20.281,8.287c0.563,0.043,1.041-0.414,1.041-0.978V57.121C48.896,56.253,47.847,55.818,47.233,56.432z   M15.911,47.942h27.422c0.868,0,1.303-1.049,0.689-1.663l-19.47-19.47c-0.403-0.403-1.074-0.382-1.439,0.055  c-4.876,5.84-7.605,12.865-8.181,20.034C14.888,47.461,15.346,47.942,15.911,47.942z M46.778,43.523  c0.614,0.614,1.663,0.179,1.663-0.689V15.102c0-0.569-0.487-1.028-1.054-0.977c-7.203,0.649-14.247,3.468-20.066,8.466  c-0.428,0.368-0.444,1.031-0.045,1.43L46.778,43.523z M57.447,47.942l27.882,0c0.566,0,1.023-0.481,0.978-1.044  c-0.583-7.274-3.381-14.403-8.393-20.293c-0.367-0.431-1.033-0.449-1.433-0.048L56.758,46.279  C56.145,46.893,56.579,47.942,57.447,47.942z M54.003,43.523l19.711-19.711c0.402-0.402,0.382-1.07-0.052-1.436  c-5.898-4.969-13.02-7.73-20.281-8.287c-0.563-0.043-1.041,0.414-1.041,0.978v27.768C52.339,43.702,53.389,44.136,54.003,43.523z   M52.686,4.712c-25.746,0-47.496,20.635-47.496,45.061c0,24.847,20.214,45.061,45.061,45.061s45.061-20.214,45.061-45.061  C95.311,24.083,76.986,4.712,52.686,4.712z M50.25,89.962c-22.161,0-40.189-18.029-40.189-40.189  c0-21.409,19.918-40.189,42.625-40.189c21.523,0,37.754,17.278,37.754,40.189C90.439,71.933,72.41,89.962,50.25,89.962z"></path>
                    </g>
                </svg>
    <h1 class="h3 mb-3 fw-normal">{{title}}</h1>
      <div class="form-floating">
      <input type="text" class="form-control mb-2" id="username" name="username" placeholder="username" autocomplete="username" required value="{% if form.username.value %}{{form.username.value}}{% endif %}">
      <label for="username">Никнейм</label>
          {% if messages %}
                {% for message in messages %}
          {% if message.tags == 'username error' %}
                        <div class="alert alert-danger alert-dismissible fade show" {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
          {% endif %}
                {% endfor %}
            {% endif %}
    </div>
    <div class="form-floating">
      <input type="email" class="form-control mb-2" id="email" name="email" placeholder="name@example.com" autocomplete="example@gmail.com" required>
      <label for="email">Email</label>
                  {% if messages %}
                {% for message in messages %}
        {% if message.tags == 'email error' %}
                        <div class="alert alert-danger alert-dismissible fade show" {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
        {% endif %}
        {% endfor %}
            {% endif %}
    </div>
    <div class="form-floating">
      <input type="password" class="form-control mb-2" id="password1" name="password1" autocomplete="new-password" placeholder="Password" required>
      <label for="password1">Пароль</label>
    </div>
      {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "passwords error" %}
                        <div class="alert alert-danger alert-dismissible fade show" {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
    <div class="form-floating">
      <input type="password" class="form-control mb-2" id="password2" name="password2" autocomplete="new-password" placeholder="Password" required>
      <label for="password2">Подтверждение пароля</label>
                  {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "password error" %}
                        <div class="alert alert-danger alert-dismissible fade show" {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
    </div>
    <button class="btn orange my-2" style="background:rgba(143, 255, 0, 0.5);" type="submit">Зарегистрироваться</button><br>
    <a href="{% url 'user:login' %}" class="link-danger" style="text-decoration:none;transition: all 1s ease-in;">Авторизоваться</a>
  </form>
        </div>
</div>
{% endblock %}

newsait/users/templates/users/users_basket.html
{% extends 'main/layout.html' %}
{% load static %}
{% load basket_tags %}

{% block title %}
    Корзина
{% endblock %}

{% block content %}
<div class="container">
    {% if basket %}
    {{basket}}
    {% else %}
    {% user_basket request as basket %}
    {% endif %}
<div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class=" bg-white mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Корзина</h3>
                                        <div class="container row not_now" id="cart-items-container" style="margin-left:0;margin-right:0;">
                                            <!-- Разметка корзины -->
                                                {% include 'basket/includes/included_cart.html' %}
                                            <!-- Закончилась разметка корзины -->

                                        </div>
                                    </div>
                                </div>
</div>
{% endblock %}