newsait/basket/urls.py
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_change/', views.basket_change, name='basket_change'),
    path('basket_remove/', views.basket_remove, name='basket_remove')
]

newsait/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('search', views.catalog, name='search'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

newsait/newsait/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'main.views.my_404_view'

urlpatterns = [
    path('product/', include('CatalogApp.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsait/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users-basket', views.users_basket, name='users-basket')
]

newsait/main/views.py
from django.db.models import Q
from django.shortcuts import render
from CatalogApp.models import Products, Categories, Countries
from django.core.paginator import Paginator
from main.utils import q_search
def index(request):
    products = Products.objects.all()[:4]
    context= {
        'products': products

    }
    return render(request, 'main/index.html',context)

def catalog(request):
    categories = Categories.objects.all()
    countries = Countries.objects.all()
    products = Products.objects.all()
    category_id = request.GET.getlist('category', 0)
    country_id = request.GET.getlist('country', 0)
    page = request.GET.get('page', 1)
    sort = request.GET.getlist('sort', None)
    query = request.GET.get('q', None)
    if query:
        products = q_search(query)
    if sort and 'd' not in sort:
        if 'DESC' in sort:
            if country_id and category_id:
                products = Products.objects.filter(
                    Q(category_id__in=category_id) & Q(country_id__in=country_id)).distinct().order_by('-cost')
            elif category_id:
                products = Products.objects.filter(category__in=category_id).distinct().order_by('-cost')
            elif country_id:
                products = Products.objects.filter(country__in=country_id).distinct().order_by('-cost')
            else:
                products = Products.objects.all().distinct().order_by('-cost')
        elif 'ASC' in sort:
            if country_id and category_id:
                products = Products.objects.filter(
                    Q(category_id__in=category_id) & Q(country_id__in=country_id)).order_by('cost')
            elif category_id:
                products = Products.objects.filter(category__in=category_id).order_by('cost')
            elif country_id:
                products = Products.objects.filter(country__in=country_id).order_by('cost')
            else:
                products = Products.objects.all().order_by('cost')
    else:
        if country_id and category_id:
            products = Products.objects.filter(
                Q(category_id__in=category_id) & Q(country_id__in=country_id))
        elif category_id:
            products = Products.objects.filter(category__in=category_id)
        elif country_id:
            products = Products.objects.filter(country__in=country_id)

    paginator = Paginator(products, 2)
    current_page = paginator.page(page)

    if sort:
        if category_id and country_id:
            country_id = [int(item) for item in country_id]
            category_id = [int(item) for item in category_id]
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select': category_id,
                'select_country': country_id,
                'select_sort': sort,
                'query': query
            }
        elif category_id:
            category_id = [int(item) for item in category_id]
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select': category_id,
                'select_sort': sort,
                'query': query
            }
        elif country_id:
            country_id = [int(item) for item in country_id]
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select_country': country_id,
                'select_sort': sort,
                'query': query
            }
        else:
            print(current_page)
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select_sort': sort,
                'query': query
            }
    else:
        if category_id and country_id:
            country_id = [int(item) for item in country_id]
            category_id = [int(item) for item in category_id]
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select': category_id,
                'select_country': country_id,
                'query': query
            }
        elif category_id:
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select': category_id,
                'query': query
            }
        elif country_id:
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'select_country': country_id,
                'query': query
            }
        else:
            context = {
                'countries': countries,
                'category': categories,
                'products': current_page,
                'query': query
            }

    return render(request, 'main/catalog.html', context)

def about(request):
    return render(request, 'main/about.html')

def contact(request):
    return render(request, 'main/contact.html')

def my_404_view(request, exception):
    context = {
        'title': 'Страница не найдена: 404',
        'error_message': 'К сожалению такая страница была не найдена, или перемещена',
    }

    return render(request, 'main/404.html', context)

newsait/main/templates/main/catalog.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
Каталог
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-between align-items-start">
        <div class="col-sm-4 col-md-4 col-lg-3 contact_modal_without">
            <form action="{% if request.GET.q %}{% url 'search' %}{% else %}{% url 'catalog' %}{% endif %}" method="get">
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{request.GET.q}}">
                {% endif %}
                <div class="dropdown mb-1">
                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu1"
                        data-bs-toggle="dropdown" aria-haspopup="true" data-bs-auto-close="false" aria-expanded="true">
                        Категории товаров
                    </button>
                    <div class="dropdown-menu" style="padding:0;" aria-labelledby="dropdownMenu1">
                        {% for category in category %}
                            <label class="text-center my-2 mx-2"><img src="{{category.icon.url}}" class="icon_plus" style="padding-right:5px;" alt="{{category.name}}"><input type="checkbox" name="category" value="{{ category.category_id }}" {% if category.category_id in select %} checked {% endif %}> {{ category.name }}</label><br><hr style="margin:0;">
                        {% endfor %}
                    </div>
                </div>
                <div class="dropdown mb-1">
                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2"
                        data-bs-toggle="dropdown" aria-haspopup="true" data-bs-auto-close="false" aria-expanded="false">
                        Страна производителя
                    </button>
                    <div class="dropdown-menu" style="padding:0;" aria-labelledby="dropdownMenu2">
                        {% for country in countries %}
                            <label class="text-center my-2 mx-2"><input type="checkbox" name="country" value="{{ country.country_id }}" {% if country.country_id in select_country %} checked {% endif %}> {{ country.name }}</label><br><hr style="margin:0;">
                        {% endfor %}
                    </div>
                </div>
                <div class="dropdown mb-1">
                    <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu3"
                        data-bs-toggle="dropdown" aria-haspopup="true" data-bs-auto-close="false" aria-expanded="false">
                        Стоимость
                    </button>
                    <div class="dropdown-menu" style="padding:0;" aria-labelledby="dropdownMenu2">
                        <label class="text-center my-2 mx-2"><input type="radio" name="sort" value="ASC" {% if 'ASC' in select_sort %} checked {% endif %}> По возрастанию</label><br><hr style="margin:0;">
                        <label class="text-center my-2 mx-2"><input type="radio" name="sort" value="DESC" {% if 'DESC' in select_sort %} checked {% endif %}> По убыванию</label><br><hr style="margin:0;">
                        <label class="text-center my-2 mx-2"><input type="radio" name="sort" value="d" {% if 'd' in select_sort %} checked {% endif %}> Без сортировки</label><br><hr style="margin:0;">
                    </div>
                </div>
                <input type="submit" value="Показать" class="btn orange" style="background: rgba(255, 138, 0,0.5);">
            </form>
        </div>

        <div class="col-sm-6 col-md-8 col-lg-8 d-flex flex-wrap align-items-center cardio">
            {% if products %}
            {% for product in products %}
            <div class="card align-items-center text-center">
                <div class="card-body">
                    <img class="card-img" src="{{product.photo.url}}" alt="{{product.name}}">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">{{product.country}} 1 кг</p>
                    <p class="card-text">{{product.cost}} Р</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'basket:basket_add' %}" class="btn btn-primary add-to-cart"
                       data-product-id="{{ product.product_id }}"
                       style="border:solid 1px;background: rgba(143, 255, 0, 0.5);color:#000;">В корзину</a>
                    {% csrf_token %}
                    {% else %}
                    <a href="{% url 'user:login' %}?message=1" class="orange btn" style="background: rgba(143, 255, 0, 0.5)">В корзину</a>
                    {% endif %}

                    <a href="product/{{product.slug}}" class="btn btn-secondary"
                       style="border:solid 1px; background: rgba(255, 138, 0,0.5);color:#000;">Подробнее</a>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <h3>Товаров по данному запросу не найдено</h3>
            {% endif %}
        </div>
    </div>
    {% if products.paginator.count > 2 %}
        <nav aria-label="Навигация" class="mx-4 text-center align-items-center">
            <ul class="pagination justify-content-center" style="margin-bottom:0;margin-top:10px;">
                <li class="page-item">
                    <a class="page-link" href="?page=1{% for cid in select %}&category={{ cid }}{% endfor %}{% for country in select_country %}&country={{ country }}{% endfor %}{% for sort in select_sort %}&sort={{sort}}{% endfor %}{% if query %}&q={{ query }}{% endif %}" aria-label="Первая">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% for page in products.paginator.page_range %}
                            <li class="page-item"><a class="page-link {% if products.number == page %} active {% endif %}" href="?page={{page}}{% for cid in select %}&category={{ cid }}{% endfor %}{% for country in select_country %}&country={{ country }}{% endfor %}{% for sort in select_sort %}&sort={{sort}}{% endfor %}{% if query %}&q={{ query }}{% endif %}">{{ page }}</a></li>
                {% endfor %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.paginator.num_pages }}{% for cid in select %}&category={{ cid }}{% endfor %}{% for country in select_country %}&country={{ country }}{% endfor %}{% for sort in select_sort %}&sort={{sort}}{% endfor %}{% if query %}&q={{ query }}{% endif %}" aria-label="Последняя">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}
    <div id="jq-notification" class="alert alert-success col-lg-3 col-md-6 col-sm-9 mt-1" style="display:none;visibility:hidden;"></div>
</div>
{% endblock %}

newsait/main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
</head>
<body>
{% block header %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light" style="padding:10px">

        <a href="/" class="navbar-brand text-decoration-none" style="margin-right:0;">
            <svg width="64px" height="64px" viewBox="0 0 100 100" class="looka-1j8o68f"
                 id="image_footer" >
                <defs id="SvgjsDefs4396">
                    <linearGradient id="SvgjsLinearGradient4401">
                        <stop id="SvgjsStop4402" stop-color="#ef4136" offset="0"></stop>
                        <stop id="SvgjsStop4403" stop-color="#fbb040" offset="1"></stop>
                    </linearGradient>
                </defs>
                <g id="SvgjsG4397" featurekey="symbolFeature-0"
                   transform="matrix(1.1096069569186666,0,0,1.1096069569186666,-5.758862815409239,-5.228467862481947)"
                   fill="url(#SvgjsLinearGradient4401)">
                    <path xmlns="http://www.w3.org/2000/svg"
                          d="M85.324,52.012H57.902c-0.868,0-1.303,1.049-0.689,1.663l19.47,19.47c0.403,0.403,1.074,0.382,1.439-0.055  c4.876-5.84,7.605-12.865,8.181-20.034C86.347,52.493,85.89,52.012,85.324,52.012z M54.457,56.432  c-0.614-0.614-1.663-0.179-1.663,0.689v27.732c0,0.569,0.487,1.028,1.054,0.977c7.203-0.649,14.247-3.468,20.066-8.466  c0.428-0.368,0.444-1.031,0.045-1.43L54.457,56.432z M43.788,52.012l-27.882,0c-0.566,0-1.023,0.481-0.978,1.044  c0.583,7.274,3.381,14.403,8.393,20.293c0.367,0.431,1.033,0.449,1.433,0.048l19.723-19.723  C45.091,53.062,44.656,52.012,43.788,52.012z M47.233,56.432L27.522,76.143c-0.402,0.402-0.383,1.07,0.052,1.436  c5.898,4.969,13.02,7.73,20.281,8.287c0.563,0.043,1.041-0.414,1.041-0.978V57.121C48.896,56.253,47.847,55.818,47.233,56.432z   M15.911,47.942h27.422c0.868,0,1.303-1.049,0.689-1.663l-19.47-19.47c-0.403-0.403-1.074-0.382-1.439,0.055  c-4.876,5.84-7.605,12.865-8.181,20.034C14.888,47.461,15.346,47.942,15.911,47.942z M46.778,43.523  c0.614,0.614,1.663,0.179,1.663-0.689V15.102c0-0.569-0.487-1.028-1.054-0.977c-7.203,0.649-14.247,3.468-20.066,8.466  c-0.428,0.368-0.444,1.031-0.045,1.43L46.778,43.523z M57.447,47.942l27.882,0c0.566,0,1.023-0.481,0.978-1.044  c-0.583-7.274-3.381-14.403-8.393-20.293c-0.367-0.431-1.033-0.449-1.433-0.048L56.758,46.279  C56.145,46.893,56.579,47.942,57.447,47.942z M54.003,43.523l19.711-19.711c0.402-0.402,0.382-1.07-0.052-1.436  c-5.898-4.969-13.02-7.73-20.281-8.287c-0.563-0.043-1.041,0.414-1.041,0.978v27.768C52.339,43.702,53.389,44.136,54.003,43.523z   M52.686,4.712c-25.746,0-47.496,20.635-47.496,45.061c0,24.847,20.214,45.061,45.061,45.061s45.061-20.214,45.061-45.061  C95.311,24.083,76.986,4.712,52.686,4.712z M50.25,89.962c-22.161,0-40.189-18.029-40.189-40.189  c0-21.409,19.918-40.189,42.625-40.189c21.523,0,37.754,17.278,37.754,40.189C90.439,71.933,72.41,89.962,50.25,89.962z"></path>
                </g>
            </svg>
            <p style="display:none; visibility:hidden;">Главная страница</p>
        </a>
        <a href="/" class="d-flex link-body-emphasis text-decoration-none" style="margin-left:10px;">
            <p class="header_effect navbar_textio" style="margin-bottom:0;font-weight:bolder;">Modern fruit</p>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto nav col-lg-12 col-md-12 col-sm-6 justify-content-around">
        {% url 'catalog' as catalogich %}
         <li class="header_effect">
                            <a href="{{catalogich}}" class="nav-link text-black navbar_textio {% if request.path == catalogich %}active_header {% endif %}">
                                Каталог
                            </a>
                        </li>
        {% url 'about' as aboutich %}
                        <li class="header_effect">
                            <a href="{{ aboutich }}" class="nav-link text-black navbar_textio {% if request.path == aboutich %}active_header {% endif %}">
                                О нас
                            </a>
                        </li>
        {% url 'contact' as contactich %}
                        <li class="header_effect">
                            <a href="{{ contactich }}" class="nav-link text-black navbar_textio {% if request.path == contactich %}active_header {% endif %}">
                                Контакты
                            </a>
                        </li>
    </ul>
  </div>
</nav>
</div>
<hr style="margin:0;">
<header>
    <div class="px-3 py-2 border-bottom mb-3 header">
        <div class="container justify-content-between align-items-center search_container_header">
            <form class="col-lg-6 mb-2 mb-lg-0 col-md-6 col-sm-6 justify-content-between d-flex align-items-center" role="search" action="{% url 'search' %}" method="get">
                <div class="col-lg-9 col-md-8 col-sm-7" style="padding-right:10px;">
                    <input type="search" name="q" class="form-control" placeholder="Поиск фруктов" aria-label="Search" style="padding-right:0;" >
                    </div>
                <div class="col-lg-2 col-md-3 col-sm-4">
                    <button type="submit" class="btn orange" style="background: rgba(143, 255, 0, 0.5);color:#000;">Найти</button>
                </div>
            </form>

            <div class="col-lg-6 col-md-6 col-sm-6">
                <ul class="nav col-12 col-lg-auto my-2 my-md-1 search_ul_header">
                    {% if user.is_authenticated %}
                    <li class="header_effect">
                        <a href="{% url 'user:profile' %}" class="nav-link text-black align-items-center text-center">
                            <img src="{% if user.image %}{{user.image.url}}{% else %}{% static 'main/img/anonymous.png' %}{% endif %}" class="d-block mx-auto icon_plus" alt="Аватар пользователя"/>
                            {{user.username}}
                        </a>
                    </li>
                    <li class="header_effect">
                        <a href="{% url 'users:users-basket' %}" class="nav-link text-black">
                            <img src="{% static 'main/img/cart_icon.png' %}" class="d-block mx-auto icon_plus" alt="Корзина"/>
                            Корзина
                        </a>
                    </li>
                    {% else %}
                        <li class="header_effect">
                        <a href="{% url 'user:login' %}" class="nav-link text-black align-items-center text-center">
                            <img src="{% static 'main/img/user_icon.png' %}" class="d-block mx-auto icon_plus" alt="Иконка войти"/>
                            Войти
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>


{% endblock %}
{% block content %}
{% endblock %}
{% block podval %}
<div class="container">
    <footer class="row row-cols-1 row-cols-sm-2    py-5 my-5 border-top justify-content-between">
        <div class="col-sm-4 col mb-3 col-lg-4 align-items-center">
            <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
                <svg width="64px" height="64px" viewBox="0 0 100 100" class="looka-1j8o68f" id="image_footer">
                    <defs id="SvgjsDefs4396">
                        <linearGradient id="SvgjsLinearGradient4401">
                            <stop id="SvgjsStop4402" stop-color="#ef4136" offset="0"></stop>
                            <stop id="SvgjsStop4403" stop-color="#fbb040" offset="1"></stop>
                        </linearGradient>
                    </defs>
                    <g id="SvgjsG4397" featurekey="symbolFeature-0"
                       transform="matrix(1.1096069569186666,0,0,1.1096069569186666,-5.758862815409239,-5.228467862481947)"
                       fill="url(#SvgjsLinearGradient4401)">
                        <path xmlns="http://www.w3.org/2000/svg"
                              d="M85.324,52.012H57.902c-0.868,0-1.303,1.049-0.689,1.663l19.47,19.47c0.403,0.403,1.074,0.382,1.439-0.055  c4.876-5.84,7.605-12.865,8.181-20.034C86.347,52.493,85.89,52.012,85.324,52.012z M54.457,56.432  c-0.614-0.614-1.663-0.179-1.663,0.689v27.732c0,0.569,0.487,1.028,1.054,0.977c7.203-0.649,14.247-3.468,20.066-8.466  c0.428-0.368,0.444-1.031,0.045-1.43L54.457,56.432z M43.788,52.012l-27.882,0c-0.566,0-1.023,0.481-0.978,1.044  c0.583,7.274,3.381,14.403,8.393,20.293c0.367,0.431,1.033,0.449,1.433,0.048l19.723-19.723  C45.091,53.062,44.656,52.012,43.788,52.012z M47.233,56.432L27.522,76.143c-0.402,0.402-0.383,1.07,0.052,1.436  c5.898,4.969,13.02,7.73,20.281,8.287c0.563,0.043,1.041-0.414,1.041-0.978V57.121C48.896,56.253,47.847,55.818,47.233,56.432z   M15.911,47.942h27.422c0.868,0,1.303-1.049,0.689-1.663l-19.47-19.47c-0.403-0.403-1.074-0.382-1.439,0.055  c-4.876,5.84-7.605,12.865-8.181,20.034C14.888,47.461,15.346,47.942,15.911,47.942z M46.778,43.523  c0.614,0.614,1.663,0.179,1.663-0.689V15.102c0-0.569-0.487-1.028-1.054-0.977c-7.203,0.649-14.247,3.468-20.066,8.466  c-0.428,0.368-0.444,1.031-0.045,1.43L46.778,43.523z M57.447,47.942l27.882,0c0.566,0,1.023-0.481,0.978-1.044  c-0.583-7.274-3.381-14.403-8.393-20.293c-0.367-0.431-1.033-0.449-1.433-0.048L56.758,46.279  C56.145,46.893,56.579,47.942,57.447,47.942z M54.003,43.523l19.711-19.711c0.402-0.402,0.382-1.07-0.052-1.436  c-5.898-4.969-13.02-7.73-20.281-8.287c-0.563-0.043-1.041,0.414-1.041,0.978v27.768C52.339,43.702,53.389,44.136,54.003,43.523z   M52.686,4.712c-25.746,0-47.496,20.635-47.496,45.061c0,24.847,20.214,45.061,45.061,45.061s45.061-20.214,45.061-45.061  C95.311,24.083,76.986,4.712,52.686,4.712z M50.25,89.962c-22.161,0-40.189-18.029-40.189-40.189  c0-21.409,19.918-40.189,42.625-40.189c21.523,0,37.754,17.278,37.754,40.189C90.439,71.933,72.41,89.962,50.25,89.962z"></path>
                    </g>
                </svg>
                <p style="margin-bottom:0;margin-left:20px;">Modern fruit</p>
            </a>

            <p class="text-body-secondary">С 1955 года магазин успешно работает</p>
        </div>


        <div class="col-sm-4 col mb-3 col-lg-4 text-center align-items-center">
            <h5>Полезные ссылки</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="{% url 'contact' %}" class="nav-link p-0 text-body-secondary">Помощь</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Политика
                    конфиденциальности</a></li>
            </ul>
        </div>

        <div class="col-sm-3 col mb-3 sol-lg-3 text-center align-items-center">
            <h5>Контакты</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2 nav-link p-0 text-body-secondary">Владимир, ул. Батурина, 28
                    example@gmail.com для вопросов
                </li>
            </ul>
            <h5>Социальные сети</h5>
            <div class="social-icons-footer text-center align-items-center mx-auto">
                <a href="https://www.facebook.com/" class="social-icon">
                    <img src="{% static 'main/img/fb.png' %}" alt="Иконка фэйсбука"/></a>
                <a href="https://vk.com/noobik_novi4ok" class="social-icon">
                    <img src="{% static 'main/img/vk.png' %}" alt="Иконка вконтакте"/></a>
                <a href="https://web.telegram.org/a/" class="social-icon">
                    <img src="{% static 'main/img/telegram.png' %}" alt="Иконка телеграма"/></a>
            </div>
        </div>
    </footer>
</div>
{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'main/js/jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'main/js/jquery-ajax.js' %}"></script>
<script src="{% static 'main/js/jquery-events.js' %}"></script>
<script src="{% static 'main/js/index.js' %}"></script>
</html>