newsait/basket/urls.py
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_change/', views.basket_change, name='basket_change'),
    path('basket_remove/', views.basket_remove, name='basket_remove')
]

newsait/main/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('search', views.catalog, name='search'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

newsait/newsait/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'main.views.my_404_view'

urlpatterns = [
    path('product/', include('CatalogApp.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls', namespace='user')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsait/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order')
]

newsait/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('users-basket', views.users_basket, name='users-basket')
]

newsait/basket/models.py
from django.db import models
from users.models import User
from CatalogApp.models import Products

class BasketQuerySet(models.QuerySet):
    def total_price(self):
        return sum(basket.products_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)
        return 0
class Basket(models.Model):
    basket_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(to=User, on_delete=models.PROTECT, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.PROTECT, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=0,verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    objects = BasketQuerySet().as_manager()
    def products_price(self):
        return round(self.product.cost * self.quantity, 2)

    def __str__(self):
        return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'

newsait/basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from CatalogApp.models import Products
from basket.models import Basket
from django.template.loader import render_to_string
from basket.utils import get_user_basket


def basket_add(request):
    product_id = request.POST.get("product_id")
    product = Products.objects.get(product_id=product_id)

    baskets = Basket.objects.filter(user=request.user,product=product)

    if baskets.exists():
        basket = baskets.first()
        if basket:
            basket.quantity += 1
            basket.save()
    else:
        Basket.objects.create(user=request.user, product=product, quantity=1)

    user_basket = get_user_basket(request)
    cart_items_html = render_to_string(
        "basket/includes/included_cart.html", {'basket': user_basket}, request=request)

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)

def basket_change(request):
    basket_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    basket = Basket.objects.get(basket_id=basket_id)

    basket.quantity = quantity
    basket.save()
    updated_quantity = basket.quantity

    user_basket = get_user_basket(request)
    cart_items_html = render_to_string(
        "basket/includes/included_cart.html", {'basket': user_basket}, request=request
    )

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "quantity": updated_quantity,
    }

    return JsonResponse(response_data)


def basket_remove(request):
    basket_id = request.POST.get("cart_id")
    basket = Basket.objects.get(basket_id=basket_id)
    quantity = basket.quantity
    basket.delete()

    user_basket = get_user_basket(request)
    cart_items_html = render_to_string(
        "basket/includes/included_cart.html", {'basket': user_basket}, request=request
    )

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }

    return JsonResponse(response_data)

newsait/basket/templates/basket/includes/included_cart.html
{% load static %}
{% load basket_tags %}
{% load url_search_tags %}
{% find_search_url request as find_search %}

{% if basket %}
{% else %}
    {% user_basket request as basket %}
{% endif %}
<div class="card mb-3 text-bg-light shadow-lg col-md-6 col-lg-12 row" style="width:100%">
    {% for cart in basket %}
    {% csrf_token %}
    <div class="card-header">
                                                    <h5 class="card-title">{{cart.product.name}}</h5>
                                                </div>
                                                <ul class="list-group list-group-flush">
                                                    <li class="list-group-item">
                                                        <div class="row text-center">
                                                            <div class="col p-0">
                                                                <div class="input-group">
                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-dark btn-sm decrement"
                                                                            data-cart-id="{{cart.basket_id}}"
                                                                                data-cart-change-url="{% url 'basket:basket_change' %}">
                                                                            {% csrf_token %}
                                                                            -</button>
                                                                    </span>

                                                                    <label>Кол-во товара
                                                                    <input type="text" class="form-control number" value="{{cart.quantity}}"
                                                                        readonly>
                                                                    </label>

                                                                    <span class="input-group-btn">
                                                                        <button type="button" class="btn btn-dark btn-sm increment"
                                                                            data-cart-id="{{cart.basket_id}}"
                                                                                data-cart-change-url="{% url 'basket:basket_change' %}">
                                                                            {% csrf_token %}
                                                                            +</button>
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            <div class="col p-0">
                                                                <p>{{ cart.product.cost }} = </p>
                                                            </div>
                                                            <div class="col p-0"><strong>{{ cart.products_price }} ₽</strong></div>
                                                            <div class="col p-0">

                                                                <a href="{% url 'basket:basket_remove' %}" class="remove-from-cart"
                                                                   data-cart-id="{{ cart.basket_id }}">
                                                                    {% csrf_token %}
                                                                    <img class="mx-1" src="{% static 'main/img/trash_icon.png' %}"
                                                                        alt="Иконка мусорки" width="16" height="16">
                                                                </a>

                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
    {% endfor %}


                                            </div>

                                        {% if basket %}
                                            <div class="column container row">
                                                <div class="card mb-3 shadow-lg">
                                                    <div class="card-footer">
                                                        <p class="float-left">Итого <strong>{{ basket.total_quantity }}</strong> товар(а) на сумму</p>
                                                        <h4 class="float-left"><strong>{{ basket.total_price }} ₽</strong></h4>
                                                    </div>
                                                </div>
                                            </div>
                                                {% url 'orders:create_order' as create_order_url %}
                                                {% url 'user:users-basket' as basketi4 %}
                                                {% if request.path == create_order_url %}
                                                {% else %}
                                                {% if request.path == basketi4 %}

                                                    <div class="col-lg-4 col-md-6 col-sm-8">
                                                    <a class="btn orange" style="background: rgba(143, 255, 0, 0.5);" href="{% url 'orders:create_order' %}">
                                                    Оформить заказ
                                                    </a>
                                                </div>
                                                {% endif %}
                                                {% if find_search == basketi4 %}
                                                <div class="col-lg-4 col-md-6 col-sm-8">
                                                    <a class="btn orange" style="background: rgba(143, 255, 0, 0.5);" href="{% url 'orders:create_order' %}">
                                                    Оформить заказ
                                                    </a>
                                                </div>
                                                {% endif %}
                                                {% endif %}


                                            </div>
                                        {% else %}
                                        <div class="col-lg-4 col-md-6 col-sm-8">
                                        <p>Корзина пуста</p>
                                            <a class="btn orange" style="background: rgba(143, 255, 0, 0.5);" href="{% url 'catalog' %}">
                                                Перейти в каталог
                                            </a>
    </div>
                                        {% endif %}